USE HOMEAWAYDB;

DROP TABLE IF EXISTS History;
DROP TABLE IF EXISTS PopularBoard;
DROP TABLE IF EXISTS ShoppingCart;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS Photo;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Booking;
DROP TABLE IF EXISTS Property;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS User;
